const faker = require('faker');

let material = [];
for (let i = 0; i < 6; i++) {
  material.push({ name: faker.lorem.word(), url: faker.internet.url() });
}
const json = [
  {
    name: 'MATEMÁTICA',
    cycle: 'I',
    credit: '',
    material,
    syllabus: faker.internet.url(),
    synonyms: ['MATEMÁTICA'],
  },
  {
    name: 'FUNDAMENTOS DE PROGRAMACIÓN',
    cycle: 'I',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['FUNDAMENTOS DE PROGRAMACIÓN'],
  },
  {
    name: 'COMUNICACIÓN Y REDACCIÓN',
    cycle: 'I',
    credit: '',
    material,
    syllabus: faker.internet.url(),
    synonyms: ['COMUNICACIÓN Y REDACCIÓN'],
  },
  {
    name: 'MATEMÁTICA DISCRETA I',
    cycle: 'I',
    credit: '',
    material,
    syllabus: faker.internet.url(),
    synonyms: ['MATEMÁTICA DISCRETA I'],
  },
  {
    name: 'METODOLOGÍA DEL TRABAJO UNVIIERSITARIO',
    cycle: 'I',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['METODOLOGÍA DEL TRABAJO UNVIIERSITARIO'],
  },
  {
    name: 'QUÍMICA',
    cycle: 'I',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['QUÍMICA'],
  },
  {
    name: 'PROGRAMACIÓN GRÁFICA',
    cycle: 'I',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['PROGRAMACIÓN GRÁFICA'],
  },
  {
    name: 'Matemática III',
    cycle: 'III',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['Matemática III'],
  },
  {
    name: 'Teoría General de Sistemas',
    cycle: 'III',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['Teoría General de Sistemas'],
  },
  {
    name: 'Teoría General de Sistemas',
    cycle: 'III',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['Teoría General de Sistemas'],
  },
  {
    name: 'ESTADISTICA Y PROBABILIDADES',
    cycle: 'III',
    credit: '',
    material,
    syllabus: faker.internet.url(),
    synonyms: ['ESTADISTICA Y PROBABILIDADES'],
  },
  {
    name: 'ESTRUCTURA DE DATOS',
    cycle: 'III',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['ESTRUCTURA DE DATOS'],
  },
  {
    name: 'ALGORITMOS Y PROGRAMACIÓN PARALELA',
    cycle: 'III',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['ALGORITMOS Y PROGRAMACIÓN PARALELA'],
  },
  {
    name: 'SISTEMAS ELÉCTRICOS Y ELECTRÓNICOS',
    cycle: 'III',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['SISTEMAS ELÉCTRICOS Y ELECTRÓNICOS'],
  },
  {
    name: 'COMPILADORES Y TEORÍA DE LENGUAJES',
    cycle: 'V',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['COMPILADORES Y TEORÍA DE LENGUAJES'],
  },
  {
    name: 'ARQUITECTURA DE COMPUTADORES',
    cycle: 'V',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['ARQUITECTURA DE COMPUTADORES'],
  },
  {
    name: 'BASE DE DATOS I ',
    cycle: 'V',
    credit: '',
    material,
    syllabus: faker.internet.url(),
    synonyms: ['BASE DE DATOS I '],
  },
  {
    name: 'Diseño de Sistemas',
    cycle: 'V',
    credit: '',
    material,
    syllabus: faker.internet.url(),
    synonyms: ['Diseño de Sistemas'],
  },
  {
    name: 'INVESTIGACIÓN DE OPERACIONES I',
    cycle: 'V',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['INVESTIGACIÓN DE OPERACIONES I'],
  },
  {
    name: 'GESTIÓN EMPRESARIAL',
    cycle: 'VII',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['GESTIÓN EMPRESARIAL'],
  },
  {
    name: 'TELEMÁTICA',
    cycle: 'VII',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['TELEMÁTICA'],
  },
  {
    name: 'DINÁMICA DE SISTEMAS',
    cycle: 'VII',
    credit: '',
    material,
    syllabus: faker.internet.url(),
    synonyms: ['DINÁMICA DE SISTEMAS'],
  },
  {
    name: 'SISTEMAS DE INFORMACIÓN',
    cycle: 'VII',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['SISTEMAS DE INFORMACIÓN'],
  },
  {
    name: 'Ingeniería de Software II',
    cycle: 'VII',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['Ingeniería de Software II'],
  },
  {
    name: 'LEGISLACIÓN INDUSTRIAL E INFORMÁTICA',
    cycle: 'VII',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['LEGISLACIÓN INDUSTRIAL E INFORMÁTICA'],
  },
  {
    name: 'TALLER DE TESIS I',
    cycle: 'IX',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['TALLER DE TESIS I', 'TESIS I'],
  },
  {
    name: 'REALIDAD VIRTUAL',
    cycle: 'IX',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['REALIDAD VIRTUAL'],
  },
  {
    name: 'SISTEMAS EXPERTOS',
    cycle: 'IX',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['SISTEMAS EXPERTOS'],
  },
  {
    name: 'PROCESAMIENTO DE IMÁGENES',
    cycle: 'IX',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['PROCESAMIENTO DE IMÁGENES'],
  },
  {
    name: 'PRÁCTICAS PRE-PROFESIONALES',
    cycle: 'IX',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['PRÁCTICAS PRE-PROFESIONALES'],
  },
  {
    name: 'ELECTIVO II',
    cycle: 'IX',
    credit: '',
    material: [],
    syllabus: faker.internet.url(),
    synonyms: ['ELECTIVO II'],
  },
];

module.exports = new Promise(async (resolve) => {
  resolve(json);
});
